### PR TITLE
Add bats-mode recipe.

### PR DESCRIPTION
**Pull request by nevsan**

### CODE REVIEW

**Comment by npostavs** [comment]
Shouldn't it be `:type github`?

**Comment by nevsan** [comment]
It could be. The GitHub page advises using MELPA to install, but it could just as easily come from GitHub. Is it better practice in el-get to prefer the GitHub source over the MELPA package?

**Comment by npostavs** [comment]
Well, it's certainly more common practice. And you can always do `M-x el-get-elpa-build-local-recipes` to get the `:type elpa` version, so it doesn't add that much.

**Comment by nevsan** [comment]
Got it. Updated.

**Pull request merged**
