### PR TITLE
Add ampl mode

### PR DESCRIPTION
**Pull request by vmiheer**

### CODE REVIEW

**Comment by stephan-cr** [comment]
I think the correct way to fix upstream, would be:

```elisp
;;;###autoload
(defun ampl-mode () ...)
```

**Comment by vmiheer** [comment]
Thanks, sorry, I missed the location while editing in github website. 🤦‍♂️
Fixed https://github.com/vmiheer/ampl-mode/blob/patch-1/emacs/ampl-mode.el.

**Comment by stephan-cr** [comment]
I wouldn't autoload [`auto-mode-alist`](https://github.com/vmiheer/ampl-mode/blob/patch-1/emacs/ampl-mode.el#L68), see https://www.gnu.org/software/emacs/manual/html_node/elisp/When-to-Autoload.html.

And I would remove

```elisp
(autoload 'ampl-mode "Ampl" "Entering Ampl mode..." t)
```

**Comment by vmiheer** [comment]
@stephan-cr, do we know what's going on with the PRs? This has been open for over a month.

**Pull request merged**
