### PR TITLE
Allow user to shallow clone when installing el-get itself.

### PR DESCRIPTION
**Pull request by yewton**
What do you think about this idea? 🤔

### CODE REVIEW

**Comment by npostavs** [comment]
Seems okay. Do you find it saves much time?

**Comment by yewton** [comment]
It saves 50-60 sec 😊 

I wrote scripts like below and run `emacs --batch -Q -l el-get-install-test.el 2>/dev/null` to test.

```elisp
(require 'benchmark)

(setq el-get-dir (make-temp-file "el-get-" 'dir))
(add-to-list 'load-path el-get-dir)
(let* ((elapsed (benchmark-elapse
                  (with-current-buffer
                      (url-retrieve-synchronously
                       "https://raw.githubusercontent.com/yewton/el-get/fa6ee7cd5e19952a3a636fb5bb0ad18491845db4/el-get-install.el")
                    (let (el-get-install-shallow-clone
                          el-get-install-skip-emacswiki-recipes)
                      (goto-char (point-max))
                      (eval-print-last-sexp)
                      (delete-directory el-get-dir 'recursive)))))
       (report  (format "%.1f seconds" elapsed)))
  (print report))
```

```
"66.1 seconds"
```

🆚 

```elisp
(require 'benchmark)

(setq el-get-dir (make-temp-file "el-get-" 'dir))
(add-to-list 'load-path el-get-dir)
(let* ((elapsed (benchmark-elapse
                  (with-current-buffer
                      (url-retrieve-synchronously
                       "https://raw.githubusercontent.com/yewton/el-get/fa6ee7cd5e19952a3a636fb5bb0ad18491845db4/el-get-install.el")
                    (let (el-get-install-shallow-clone
                          el-get-install-skip-emacswiki-recipes)
                      (goto-char (point-max))
                      (eval-print-last-sexp)
                      (delete-directory el-get-dir 'recursive)))))
       (report  (format "%.1f seconds" elapsed)))
  (print report))
```

```
"12.2 seconds"
```

**Comment by npostavs** [comment]
Cool, sounds worthwhile then. Perhaps we could mention the new option in the manual (under the "Installing" node)?

**Comment by yewton** [comment]
I will do it!

(By the way, I wonder if they read about "installing" in the info file before installing it 🤔 )

**Comment by npostavs** [comment]
> (By the way, I wonder if they read about "installing" in the info file before installing it 🤔 )

Probably not, but I don't know where else to put it.

**Comment by yewton** [comment]
I've added to `el-get.texi` !

But `texi2info` or `makeinfo` will generate large diffs on `el-get.info` ...
How should I generate it? 😖

**Comment by npostavs** [comment]
I regenerated with makeinfo 4.13, the diff seems not too bad that way.

**Comment by yewton** [comment]
Thank you!

**Pull request merged**
