### PR TITLE
fix jedi-core recipe (download raw, not HTML)

### PR DESCRIPTION
**Pull request by hmeine**

### CODE REVIEW

**Comment by hmeine** [comment]
This is the first time I edited a recipe.  I also noticed that jedi-core depends on epc and python-environment.  Should I add these as dependencies?

**Comment by npostavs** [comment]
> I also noticed that jedi-core depends on epc and python-environment. Should I add these as dependencies?

Yup, probably. If you have the recipe open `M-x el-get-auto-update-dependencies` should write the dependencies for you.

**Comment by hmeine** [comment]
Interesting, thanks for the hint.  Unfortunately, the dependencies also contain auto-completion, which seems to reflect the truth, namely that I cannot use jedi-core with company-jedi, but ac will automatically be installed, activated and used.

**Comment by npostavs** [comment]
> Unfortunately, the dependencies also contain auto-completion

Do you mean the dependencies written by `el-get-auto-update-dependencies`? I can't see why, it could be a bug in `el-get-auto-update-dependencies`.

**Comment by hmeine** [comment]
Yes, I mean that.  I also see AC being installed and activated, without any .emacs entries or relevant customized variables.  When I tried el-get-remove auto-completion, I got complaints about two packages not being found.

For now, I gave up.  I spent too long trying to get this running, and don't have the time ATM.  Hope my feedback was at least better than nothing.

**Comment by npostavs** [comment]
I've cherry picked this to `master` as 28c168434d17784943c0b229055c9fa77d083dd3, and added dependencies in 9bc149f1c715eb250f79527c53023c1ac3264374. Not really sure about the `auto-complete` thing, if you find time to investigate more, please open a new issue.

**Pull request closed without merging**
