### PR TITLE
Added agda-input recipe

### PR DESCRIPTION
**Pull request by nyraghu**
Agda input is an input method for easily typing mathematical and other Unicode characters.  The output of the recipe checker is attached as a text file.

[agda-input.txt](https://github.com/dimitri/el-get/files/235457/agda-input.txt)

### CODE REVIEW

**Comment by npostavs** [comment]
> The output of the recipe checker is attached as a text file.

Just the output from `M-x el-get-check-recipe` should be enough (and short enough to paste inline).

**Comment by nyraghu** [comment]
> Just the output from M-x el-get-check-recipe should be enough (and short enough to paste inline).

Oops, when I saw the instruction in the el-get manual to paste the recipe checker result in the pull request comment, I misunderstood it to mean the output of test-recipe.sh, and not check-recipe.sh or el-get-check-recipe.  Will do the right thing next time!

**Comment by npostavs** [comment]
Maybe we need to clarify that page. Though most people don't bother reading it at all, since I seldom see any output from checker or tester posted!

**Comment by nyraghu** [comment]
> Just the output from M-x el-get-check-recipe should be enough
I'm curious if the submitted recipes are tested with test-recipe.sh by travis.

**Comment by npostavs** [comment]
> I'm curious if the submitted recipes are tested with test-recipe.sh by travis.

No, just check-recipe with some checks disabled (due to existing recipes failing them). See `.travis.yml` and `test/travis-ci.sh`.

**Pull request merged**
