### PR TITLE
Fix `el-get-bundle` callsite identifier generation

### PR DESCRIPTION
**Pull request by tarao**
The callsite identifier must include only valid characters for path names.  Characters other than `/` were replaced to `_` but this was not enough for example for GNU Emacs on Windows, where `:` appears after the drive letter of a callsite path.

### CODE REVIEW

**Comment by npostavs** [comment]
`make-backup-file-name-1` deals with a similar problem, in addtion to replacing the drive name they also have
```elisp
	      ;; Replace any invalid file-name characters (for the
	      ;; case of backing up remote files).
	      (setq file (expand-file-name (convert-standard-filename file)))
```

**Comment by tarao** [comment]
> `convert-standard-filename`

Done: f7b45e2

**Comment by tarao** [comment]
I found that we have wrong description of this pull request.

> must include only valid characters for path names

"must include only valid characters for **file names**" is correct.

> Characters other than `/`

"Characters **no** other than `/`" is correct.

**Comment by npostavs** [comment]
Feel free to rebase/reword/merge.

**Pull request merged**
