### PR TITLE
Update magit.

### PR DESCRIPTION
**Pull request by Pitometsu**
please, merge to master.

### CODE REVIEW

**Comment by Pitometsu** [comment]
According to https://github.com/dimitri/el-get/pull/2145
it should use :branch master as well yet.

**Comment by Pitometsu** [comment]
@npostavs please, merge `:build/darwin` as well!

**Comment by npostavs** [comment]
oh, oops, didn't notice you had added that. I just moved the `EMACSBIN` param into the other `:build/`s instead, it shouldn't cause any harm. 450c6406cf7567dc01eb41314178d14d87b54ce7

**Comment by Pitometsu** [comment]
```
make: *** No rule to make target `docs'.  Stop.
```
Please, add `"lisp"` instead of `"docs"` too.

**Comment by npostavs** [comment]
huh? Are you installing `next`? The recipe as it is right now works for me.

**Comment by Pitometsu** [comment]
@npostavs oh, sorry, u right, it's ok now.

**Pull request closed without merging**
