### PR TITLE
Added opam-mode recipe.

### PR DESCRIPTION
**Pull request by sagotch**
Note: `features` are required, how to (and why) avoid it ?

### CODE REVIEW

**Comment by npostavs** [comment]
It's preferred to autoload packages so that they can be installed without increasing startup load time. You can achieve this by adding `;;;###autoload` on the lines just before the main entry points to your package, in your case `(defun opam-mode ...` and `(defun opam-url-mode ...`.

You should also add `;;;###autoload` before `(add-to-list 'auto-mode-alist...)` calls so your mode will be activated (and loaded) when the user opens an applicable file.

**Comment by sagotch** [comment]
Thanks! I'll try it and edit my recipe. **please do not merge**

**Comment by sagotch** [comment]
`features` not required anymore. Thank you!

**Comment by npostavs** [comment]
By the way, I don't think there's much point in `provide`ing features that aren't the same as the file name.

**Comment by sagotch** [comment]
Why not?

`opam-mode` and `opam-url-mode` are meant to be used with different files, but to work together.

**Comment by npostavs** [comment]
Because if you `(require 'opam-url-mode)` before `opam-mode.el` is loaded it won't work, it would search for `opam-url-mode.el`. Defining both modes is fine, but the require/provide thing really works with file names.

**Comment by sagotch** [comment]
I thought that you needed to provide both mode to be able to use them... but you do not.

Noted, and fixed :+1:

**Pull request merged**
