### PR TITLE
Replace missing dependency inflection with jump on clj-refactor

### PR DESCRIPTION
**Pull request by f0086**
"inflection" is no longer part of elpa and it is now found in
the "jump" package.

### CODE REVIEW

**Comment by f0086** [comment]
Yes, the `inflections.rcp` exists, but as I said, it is no longer part of elpa.
I can install `jump` over el-get.

**Comment by npostavs** [comment]
> Yes, the `inflections.rcp` exists, but as I said, it is no longer part of elpa.

Then we should remove that recipe, since it doesn't work.

> I can install `jump` over el-get.

Don't we need to add a recipe for that?

> `Debugger entered--Lisp error: (wrong-type-argument arrayp nil)`

Hmm, that error should be more user-friendly.

**Comment by f0086** [comment]
I've added the jump package and removed the inflection package.
All dependencies are adjusted accordingly.

**Comment by npostavs** [comment]
Thanks!

**Comment by npostavs** [comment]
> > `Debugger entered--Lisp error: (wrong-type-argument arrayp nil)`
> 
> Hmm, that error should be more user-friendly.
> 

This should now say something like 
`Debugger entered--Lisp error: (error "Couln’t find package ‘inflections’")`

ddf128195bc8e1184ecc8804df9a80b5a90156e0

**Pull request merged**
