### PR TITLE
Add docker-tramp recipe

### PR DESCRIPTION
**Pull request by Yuki-Inoue**
The definition is taken from that of MELPA:
    https://melpa.org/#/docker-tramp

Note this is included in the dependency of recipe/docker.rcp .

### CODE REVIEW

**Comment by npostavs** [comment]
> Note this is included in the dependency of recipe/docker.rcp .

"*is* included" or "*should* be" included? I don't see it there now.

**Comment by Yuki-Inoue** [comment]
@npostavs Oh yeah,,, it "is not included" now but "should be included".  I'll modify the docker.rcp too...

**Comment by Yuki-Inoue** [comment]
@Silex Adding docker-tramp to el-get.

**Comment by Silex** [comment]
:+1: already the case in docker.el

``` elisp
;; Package-Requires: ((emacs "24.4") (dash "2.12.1") (docker-tramp "0.1") (magit-popup "2.6.0") (s "1.11.0") (tablist "0.70"))
```

**Pull request closed without merging**
