### PR TITLE
Update magit recipes

### PR DESCRIPTION
**Pull request by syohex**
- Update magit dependencies
- with-editor is hosted own repository now
- Add async recipe

See also
- https://github.com/milkypostman/melpa/pull/3542
- https://github.com/magit/magit/blob/b549e4e0e7d57954eef9011329a53641f3807dcf/lisp/magit.el#L19

### CODE REVIEW

**Comment by npostavs** [comment]
We already have async under the name emacs-async.

**Comment by syohex** [comment]
Oh, I mistook.

**Comment by syohex** [comment]
Thanks for reviewing. I have updated.

**Comment by npostavs** [comment]
Merged, I just removed "add async recipe" from commit message.

The async vs emacs-async is a bit confusing, it might make sense to rename.

**Pull request closed without merging**
