### PR TITLE
Fixed jedi-core and company-jedi recipes

### LINKED ISSUE #2350: error with dependencies in jedi-core.rcp
From [Melpa recipe](https://github.com/melpa/melpa/blob/master/recipes/jedi-core) we need to download few files
```lisp
files ("jedi-core.el" "jediepcserver.py" "Makefile" "setup.py"))
```
but in [your recipe](https://github.com/dimitri/el-get/blob/master/recipes/jedi-core.rcp) it\`s download only .el file
Could you fix this error? jedi:install-server doesn\`t work without this files

### PR DESCRIPTION
**Pull request by Crandel**
fixes #2350.

### CODE REVIEW

**Comment by npostavs** [comment]
So the only significant difference between jedi and jedi-core after this would be that jedi depends on auto-complete, and jedi-core doesn't, right?

I think you should add `:compile "jedi-core.el"` so that el-get won't try to compile jedi.el (it has `(require 'auto-complete)` which would cause compilation failure if you don't have that installed, I think.

**Comment by Crandel** [comment]
Thank you for helping, It`s my first public pull request: )

**Comment by npostavs** [comment]
Okay, I think if you can just add to the description field an explanation about the difference between jedi-core and jedi recipes it will be good to go.

**Comment by npostavs** [comment]
Squashed to `master`, thanks for working on this :)

**Pull request merged**
