### PR TITLE
Fix compilation breakage on Emacs 28 feature/native-comp

### PR DESCRIPTION
**Pull request by vedang**
Pass the correct number of arguments to `define-obsolete-function-alias`

Otherwise, the code breaks on the feature/native-comp branch for Emacs 28.

Update: 2021-02-14 
I've rebased on top of the latest el-get and made some more changes for breaking functionality. This is tested against Emacs 28.0.50 built from the the top of `feature/native-comp` as of 2021-02-13. 

(I needed to make these changes in order to get `el-get` to install new recipes)

### CODE REVIEW

**Comment by MithicSpirit** [comment]
Dupe of #2796

**Comment by vedang** [comment]
Ack, sorry for not noticing #2796 in the PRs. Please choose whichever one you think is appropriate and merge it in!

**Comment by vedang** [comment]
I've pushed some more commits and updated the description with the following: 

> Update: 2021-02-14
> I've rebased on top of the latest el-get and made some more changes for breaking functionality. This is tested against Emacs 28.0.50 built from the the top of feature/native-comp as of 2021-02-13.
> 
> (I needed to make these changes in order to get el-get to install new recipes)

**Comment by vedang** [comment]
Gentle reminder to get this merged in, as `el-get` is broken on Emacs 28 right now. I looked at the test failure (when travis-ci was still functional) and I don't think it is related to my changes here. I have also run the tests locally with `test/run-ert.sh` and they are passing:

```
Ran 10 tests, 10 results as expected, 0 unexpected (2021-02-22 09:52:42+0530, 14.547724 sec)
1 expected failures
```

**Comment by tarao** [comment]
I confirmed that this fixes problems on Emacs 28 and includes fixes done separately in #2796 and #2797.  I'm going to get this merged unless I hear objections from other people (especially maintainers).  I will wait until tomorrow (in JST).

**Pull request merged**
