### PR TITLE
Add Emacs 27.1 to CI

### PR DESCRIPTION
**Pull request by stephan-cr**
Build el-get for Emacs 27.1 as well.

### CODE REVIEW

**Comment by stephan-cr** [comment]
The checks for Emacs 27.1 fail, because `byte-compile -Werror *.el methods/*.el` turns warnings like `Package cl is deprecated` into errors.

**Comment by stephan-cr** [comment]
I would rebase this branch as soon as #2802 is merged. I hope that project is still alive.

**Comment by tarao** [comment]
@stephan-cr 
I've added Emacs 27.2 to CI during switching from Travis CI to GitHub Actions in #2836.
Could you continue #2802 with this?

**Comment by stephan-cr** [comment]
@tarao I saw your changes. Great move! But I wonder why `byte-compile -Werror *.el methods/*.el` doesn't fail for Emacs 27.2.

**Comment by tarao** [comment]
@stephan-cr 

I had the same question and looked into the test code.  It seems that byte-compilation is skipped for recipe-only changes (non-code changes) except on Emacs 24.5.  So, it should do byte-compilation test on your `replace-cl` branch after rebasing `master` branch.

**Comment by stephan-cr** [comment]
Closed, because el-get moved to Github Actions.

**Pull request closed without merging**
